### ISSUE TITLE
Save Collection button is not visible

### ISSUE THREAD

**Issue by jazahn** [Harvard-ATG/media_management_lti#28]
Inside the iframe, the "save collections" button is being cut off. This seems to only happen when there's more than one line of images in the image lib. So the height is being calculated and then, when the images finish loading, they push the button below the bottom of the page. 

<img width="1197" alt="screen shot 2016-03-28 at 11 19 52 am" src="https://cloud.githubusercontent.com/assets/1198016/14081172/623b6f80-f4d7-11e5-80e8-0c0349d03809.png">

===
### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit tests - at least one unit test per story; one per acceptance criterion (if possible)
- [ ] Regression tests - at least one regression test per bug fix
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria
- [ ] Deployed to QA
- [ ] Release notes

**Comment by Vittorio2015** [comment]
I reproduced the same experience by adding the first image to an empty collection (sorry about your chin, Jazahn!). Would there be a way, upon the selection of a new image in the Image Library, to auto-scroll to the bottom of the iframe as we do when we use anchor links? 

![image](https://cloud.githubusercontent.com/assets/12190138/14141700/b38ceed6-f64e-11e5-81ce-a75eccae64bc.png)

**Comment by jazahn** [comment]
This bug is no longer an issue with the new layout.
