### ISSUE TITLE
Collection Badge

### ISSUE THREAD

**Issue by jazahn** [Harvard-ATG/media_management_lti#36]
When adding or removing images to/from a collection, the badge won't update until the page is refreshed.

<img width="93" alt="screen shot 2016-03-30 at 9 53 32 am" src="https://cloud.githubusercontent.com/assets/1198016/14144358/5138707a-f65d-11e5-8617-fe070b75f3f9.png">

===
### Definition of Done

- [x] Check into version control
- [x] Code review
- [ ] Unit tests - at least one unit test per story; one per acceptance criterion (if possible)
- [x] Regression tests - at least one regression test per bug fix
- [x] Passes continuous integration tests (automation via Travis)
- [x] Meets acceptance criteria
- [x] Deployed to QA
- [ ] Release notes

**Comment by arthurian** [comment]
PR waiting for review.

**Comment by arthurian** [comment]
Code review done (merged to master), but still needs a unit test.
