### ISSUE TITLE
UX: Metadata Bootstrap UI

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/media_management_lti#42]
As a developer, I want to make the UI for metadata use more of the bootstrap look and feel.

### Acceptance Criteria

- [ ] Implement Vittorio's proposed improvements to the metadata fields using bootstrap: https://github.com/Harvard-ATG/ATG-UX/commit/22ce748672a849318d00f4416f7a036cad95a925

### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit tests - at least one unit test per story; one per acceptance criterion (if possible)
- [ ] Regression tests - at least one regression test per bug fix
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria
- [ ] Deployed to QA
- [ ] Release notes

**Comment by jazahn** [comment]
Duplicated in #37
