### ISSUE TITLE
Fix Drag and Drop width

### ISSUE THREAD

**Issue by jazahn** [Harvard-ATG/media_management_lti#58]
As a user 
I want the Drag and Drop width to be the size of the space it's in
So that it centers the text and closes the div

### Acceptance Criteria

- [ ] the box is closed
- [ ] the text is centered

![screen shot 2016-04-13 at 1 52 13 pm](https://cloud.githubusercontent.com/assets/1198016/14503652/09bd7240-017f-11e6-92f3-6b6b51eb9575.png)

### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit tests - at least one unit test per story; one per acceptance criterion (if possible)
- [ ] Regression tests - at least one regression test per bug fix
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria
- [ ] Deployed to QA
- [ ] Release notes

**Comment by arthurian** [comment]
This is fixed by #61.
