### ISSUE TITLE
UI - Indicate how many available images are in the image library

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#83]
As a user who would like to immediately know (without having to scroll) how many available images are in the image library, especially I just added a few.
I want to see the total of available images (all the images in the image library, minus the ones I have already imported in this collection) within the viewing area
So that I don't need to scroll and manually count all the images, or verifying that the images I just added were added to the total count

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14866985/4a42d6c8-0c94-11e6-8898-211fe2659736.png)

### Acceptance Criteria

- [x] Add a text string to the Image Library header to show '[# of all the image library images minus the ones that have been added to this collection] available images in this image library'

### Definition of Done

- [x] Check into version control
- [ ] Code review
- [x] Unit/Regression Tests
- [x] Passes continuous integration tests (automation via Travis)
- [x] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I think this one needs a little more discussion. Is that the right place to put the number?
