### ISSUE TITLE
UI - Image size limit definition

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#84]
As an English speaking user (as opposed to 'techie' speaking user) 
I want see the image size limit of an imported image to the Image Library as  'Limit 20.00MB.' without decimals (unless there will be instance to display decimals)
So that I don't get even more confused about what 'MB' means 

### Acceptance Criteria

- [x] Eliminate the decimals in the 'Limit 20.00MB.' string so that it reads 'Limit 20 MB.'
- [x] While you are at it, you may want to consider 'Imported images cannot exceed 20 MB.'

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14867411/62063dde-0c96-11e6-80e7-34ccc1274f8d.png)

### Definition of Done

- [x] Check into version control
- [ ] Code review
- [x] Unit/Regression Tests
- [x] Passes continuous integration tests (automation via Travis)
- [x] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I discussed this today and we're adding to the backlog for the next sprint.
