### ISSUE TITLE
UI - Image Library - Reposition the alert

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#85]
As a user trying to import a large file in the Image Library 
I want to see the alert in proximity of the area that just triggered the alert, instead than on the very top of the interface 
So that I may not miss that alert if I happen to had scrolled that top area out of the view (as 'some' PO did at the April 27 demo!) 

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14867737/f2f31d8e-0c97-11e6-8191-de4fe9f119b5.png)

### Acceptance Criteria

- [x] Move the alert right above the Drag & Drop area
- [x] While you are at it, you may want to consider the test edits to the alert message suggested on [issue #84](https://github.com/Harvard-ATG/media_management_lti/issues/84) 

### Definition of Done

- [x] Check into version control
- [ ] Code review
- [x] Unit/Regression Tests
- [x] Passes continuous integration tests (automation via Travis)
- [x] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I think we should revisit this one later. Not adding to backlog for next sprint.

**Comment by arthurian** [comment]
Note: Vittorio will follow-up on this.
