### ISSUE TITLE
UI - Collection description information

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#86]
As a user who doesn't know (or remember) whether the description has been added to a collection  
I want the button next to the collection name to indicate whether there is no available description ('Add a Description') or there is a description ('Edit Description')
So that I can, at a glance, see whether the description of a collection is already available or absent (so that I can add one) 

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14868077/ac950026-0c99-11e6-8d47-e324bf8395b1.png)
![image](https://cloud.githubusercontent.com/assets/12190138/14868367/3c751298-0c9b-11e6-9f10-24fe894c1b05.png)

### Acceptance Criteria

- [x] When the text area of the description is empty or it just has 'No description', the button next to the collection name should show 'Add a Description'
- [x] When the text area of the description is not empty or it has text other than ''No description', the button next to the collection name should show 'Edit Description'
- [x] While you are at it, please vertical align the Description label (see above second example) with something like 'vertical-align:top; margin-top:.75em;' to match the position of the Collection label

### Definition of Done

- [x] Check into version control
- [ ] Code review
- [x] Unit/Regression Tests
- [x] Passes continuous integration tests (automation via Travis)
- [x] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I discussed this today and we're adding to the backlog for the next sprint.
