### ISSUE TITLE
UI - Saving the description of a collection

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#87]
As a user who just added/edited the description of a collection 
I want the alert to refer to the information I just submitted 
So that I can confirm that the description I just added/edited has been saved 

### Acceptance Criteria

- [x] If possible to distinguish between (1) saving the images I just added to/deleted from a collection (2) added/edited a collection description or (3) added/edited a collection name, specify what has been has been edited, such as (1) The collection is saved, (2) The collection name is saved or (3) The collection description is saved
- [x] While you are at it, please remove the div.row that wraps the div.notifications.ng-scope so that the alert aligns (width-wise) with the panel below

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14869071/29f0017e-0c9f-11e6-8d44-5104f308184a.png)

### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit/Regression Tests
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I discussed this today and we're adding to the backlog for the next sprint.
