### ISSUE TITLE
UI - Collection image thumbnails

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#88]
As a user who is adding images to a collection, and realizes that certain images don't have names or other information
I want edit the information of an image I have already imported in a collection 
So that I don't have to remove it from the collection if I want to edit the image information

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14869378/025587c2-0ca1-11e6-82c3-c64c36aba6b9.png)

### Acceptance Criteria

- [x] As shown in the above example, allow an image imported in a collection to show also the 'expand' icon so that it can be edited from here
- [x] While you are at it, please consider to replace the expand glyphicon-resize-full icon to the glyphicon-cog or even the glyphicon-info-sign as indicated in [this commit](https://github.com/Harvard-ATG/ATG-UX/commit/26206ca383a62242b6ca76f7c5ca1e72cbfcb80f#diff-4c7e3b9842542ff33aa93c73cc930bd9)

### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit/Regression Tests
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I discussed this today and we're adding to the backlog for the next sprint.

**Comment by arthurian** [comment]
Note: need to make sure user is aware they are editing the image in *all* collections.

**Comment by jazahn** [comment]
we don't currently have the collection information at the image level -- indicating it more than we currently do with the message would be more work than I'm willing to do for this right now

**Comment by Vittorio2015** [comment]
Just as a reminder, for when and if this interface is implemented, the user shall be offered an option to:
- either and purposely change an image on all collections (an dI believe also the image library), 
- or make the image changes on a copy of that image, and therefore not affecting that image instance on all other collections and the image library.
