### ISSUE TITLE
UI - Visual alignment of panel headers

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/media_management_lti#89]
As a user with an eye for the details 
I want the height of the panel headers of a collection and the adjacent Image Library to match
So that the visual elements of this interface align 

### Example
![image](https://cloud.githubusercontent.com/assets/12190138/14869785/d4360f58-0ca3-11e6-9ebf-ad0feea44f7a.png)

### Acceptance Criteria

- [ ] Please add padding:.7em to the h3.panel-title with the Image Library header
- [ ] Don't laugh!

### Definition of Done

- [ ] Check into version control
- [ ] Code review
- [ ] Unit/Regression Tests
- [ ] Passes continuous integration tests (automation via Travis)
- [ ] Meets acceptance criteria

**Comment by arthurian** [comment]
@brandonATG and I discussed this today and we're adding to the backlog for the next sprint.

**Comment by jazahn** [comment]
I'm not sure we can meet the second acceptance criteria.
